language: python
python:
  - "3.7"

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt


sudo: required
services:
  - postgresql
#addons:
#  postgresql: "9.6"

before_script:
  - psql -c 'create database bookstore;' -U postgres
# Run the unit test
script:
  #- export PATHONPATH=`pwd`
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python init_database.py
  - coverage run --timid --branch --source fe,be --concurrency=thread -m pytest -v --ignore=fe/data
env:
  global:
  - PGPORT=5432
# Push the results back to codecov
after_success:
  - coverage combine
  - coverage report
  - python app.py &
  - python run.py
  - cat bench.log
  - codecov
  - bash <(curl -s https://codecov.io/bash)